apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin
home: https://jellyfin.org/
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/refs/heads/master/branding/NSIS/modern-install.png
type: application
version: 0.2.1
appVersion: "10.10.6"
kubeVersion: ">=1.19.0-0"
keywords:
  - jellyfin
  - media
  - Personal Media Server
maintainers:
  - name: kriegalex
    email: kriegalex@gmail.com
sources:
- https://github.com/jellyfin/jellyfin
