
nameOverride: ""
fullnameOverride: ""

image:
  repository: jellyfin/jellyfin
  # If unset use "latest"
  tag: latest
  pullPolicy: IfNotPresent

statefulSet:
  # optional extra annotations to add to the service resource
  annotations: {}
  # optional extra annotations to add to the pods in the statefulset
  podAnnotations: {}

service:
  type: ClusterIP
  port: 8096

ingress:
  # Specify if an ingress resource for the pms server should be created or not
  enabled: false

  # The ingress class that should be used
  ingressClassName: "nginx"

  # The url to use for the ingress reverse proxy to point at this pms instance
  url: ""

  # Custom annotations to put on the ingress resource
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Common Labels for all resources created by this chart.
commonLabels: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # If the service account token should be auto mounted
  automountServiceAccountToken: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

persistence:
  # This is the directory containing the server configuration files. 
  config:
    enabled: true
    mountPath: /config
    subPath: ""
    existingClaim: ""
    size: 20Gi # can grow to 100GB+ for big libraries
    storageClassName: null
  # This is the directory containing the server cache (metadata for the libraries).
  cache:
    enabled: true
    mountPath: /cache
    subPath: ""
    existingClaim: ""
    size: 5Gi
    storageClassName: null

# Not useful for now. Future-proofing
extraEnv: []

# Optionally specify additional volumes for the pod.
extraVolumes: []
# extraVolumes:
#   - name: media
#     persistentVolumeClaim:
#       claimName: nfs-media

# Optionally specify additional volume mounts for the media.
extraVolumeMounts: []
# extraVolumeMounts:
#   - name: media
#     mountPath: /media

# Not useful for now. Future-proofing
extraHosts: []
