{{- if not .Values.ntfyAlertmanager.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-ntfy.fullname" . }}
  annotations:
    confighash: {{ .Values.ntfyAlertmanager | toYaml | sha256sum | trunc 32 }}
  labels:
    {{- include "alertmanager-ntfy.labels" . | nindent 4 }}
stringData:
  {{- with .Values.ntfyAlertmanager }}
  config: |
    http-address :{{ .port }}
    log-level {{ .logLevel }}
    {{- with .logFormat }}
    log-format {{ . }}
    {{- end }}
    {{- with .baseURL }}
    base-url {{ . }}
    {{- end }}
    {{- with .alertMode }}
    alert-mode {{ . }}
    {{- end }}
    {{- if and .user .password }}
    user {{ .user }}
    password {{ .password }}
    {{- end }}
    {{- with .ntfy }}
    ntfy {
      {{- with .topic }}
      topic {{ . }}
      {{- end }}
      {{- with .server }}
      server {{ . }}
      {{- end }}
      {{- if and .user .password }}
      user {{ .user }}
      password {{ .password }}
      {{- end }}
      {{- with .accessToken }}
      access-token {{ . }}
      {{- end }}
      {{- with .certificateFingerprint }}
      certificate-fingerprint {{ . }}
      {{- end }}
      {{- with .emailAddress }}
      email-address {{ . }}
      {{- end }}
      {{- with .call }}
      call {{ . }}
      {{- end }}
      {{- if kindIs "bool" .markdown }}
      markdown {{ .markdown }}
      {{- end }}
      {{- with .generatorUrlLabel }}
      generator-url-label {{ . | quote }}
      {{- end }}
    {{- end }}
    {{- $tpath := include "alertmanager-ntfy.templatePath" $ }}
    {{- with $tpath }}
      template-path {{ . | quote }}
    {{- end }}
    {{- if .ntfy }}
    }
    {{- end }}
    {{- with .labels }}
    labels {
      order {{ .order | join "," | quote }}
      {{- range .entries }}
      {{ .label }} {{ .value | quote }} {
        {{- with .priority }}
        priority {{ . }}
        {{- end }}
        {{- with .tags }}
        tags {{ . | join "," | quote }}
        {{- end }}
        {{- with .icon }}
        icon {{ . | quote }}
        {{- end }}
        {{- with .emailAddress }}
        email-address {{ . }}
        {{- end }}
        {{- with .call }}
        call {{ . }}
        {{- end }}
        {{- with .topic }}
        topic {{ . }}
        {{- end }}
      }
      {{- end }}
    }
    {{- end }}
    {{- with .resolved }}
    resolved {
        {{- with .updateNotification }}
        update-notification {{ . }}
        {{- end }}
        {{- with .tags }}
        tags {{ . | join "," | quote }}
        {{- end }}
        {{- with .priority }}
        priority {{ . }}
        {{- end }}
        {{- with .icon }}
        icon {{ . | quote }}
        {{- end }}
    }
    {{- end }}
    {{- with .alertmanager }}
    {{- if or .silenceDuration .user .url }}
    alertmanager {
      {{- with .silenceDuration }}
      silence-duration {{ . }}
      {{- end }}
      {{- if and .user .password }}
      user {{ .user }}
      password {{ .password }}
      {{- end }}
      {{- with .url }}
      url {{ . }}
      {{- end }}
    }
    {{- end }}
    {{- end }}
    {{- with .cache }}
    {{- if .type }}
    cache {
      type {{ .type }}
      {{- with .duration }}
      duration {{ . }}
      {{- end }}
      {{- with .cleanupInterval }}
      cleanup-interval {{ . }}
      {{- end }}
      {{- with .redisURL }}
      redis-url {{ . }}
      {{- end }}
    }
    {{- end }}
    {{- end }}
  {{- if and .template.enabled .template.body }}
  template.tmpl: |
{{ .template.body | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
