apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nostr-strfry.fullname" . }}
  labels:
    {{- include "nostr-strfry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nostr-strfry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nostr-strfry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "nostr-strfry.serviceAccountName" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7777
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/strfry.conf
              subPath: strfry.conf
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/strfry-db
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "nostr-strfry.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "nostr-strfry.fullname" . }}
        {{- end }}
{{- if .Values.nip05.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nostr-strfry.fullname" . }}-nip05
  labels:
    {{- include "nostr-strfry.labels" . | nindent 4 }}
    app.kubernetes.io/component: nip05
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nostr-strfry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nip05
  template:
    metadata:
      labels:
        {{- include "nostr-strfry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nip05
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nip05.image.repository }}:{{ .Values.nip05.image.tag | default "alpine" }}
        imagePullPolicy: {{ .Values.nip05.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nip05-config
          mountPath: /usr/share/nginx/html/.well-known
      volumes:
      - name: nip05-config
        configMap:
          name: {{ include "nostr-strfry.fullname" . }}-nip05
{{- end }}
