apiVersion: v2
name: paperless-ngx
description: A Helm chart for Paperless-ngx
home: https://docs.paperless-ngx.com/
icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/b948750/src-ui/src/assets/logo-notext.svg
type: application
version: 0.1.1
kubeVersion: ">=1.19.0-0"
appVersion: "2.11.2"
keywords:
  - documents
  - ocr
  - paper
dependencies:
  - name: postgresql
    version: 14.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 16.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.6.4
    condition: redis.enabled
sources:
- https://github.com/paperless-ngx/paperless-ngx
