# charts/vendored-charts/paperless-ngx/Chart.yaml
apiVersion: v2
name: paperless-ngx
version: 0.23.0
dependencies:
  - name: paperless-ngx
    version: 0.23.0
    repository: https://charts.gabe565.com
