apiVersion: v1
kind: Service
metadata:
  name: {{ include "actual-budget.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5006
  selector:
    app: {{ include "actual-budget.fullname" . }}
