apiVersion: v2
name: clonarr
description: A Helm chart for Clonarr, a visual TRaSH-Guides sync tool for Radarr and Sonarr (Custom Formats, Quality Profiles, Scores, Quality Sizes).
home: https://github.com/prophetse7en/clonarr
icon: https://raw.githubusercontent.com/prophetse7en/clonarr/main/static/logo.png
type: application
version: 0.9.0
appVersion: "latest"
kubeVersion: ">=1.19.0-0"
keywords:
  - clonarr
  - radarr
  - sonarr
  - trash-guides
  - custom-formats
  - media
maintainers:
  - name: kriegalex
    email: kriegalex@gmail.com
sources:
  - https://github.com/prophetse7en/clonarr
  - https://github.com/kriegalex/k8s-charts/tree/main/charts/clonarr
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
deprecated: false
annotations:
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/kriegalex/k8s-charts/tree/main/charts/clonarr
    - name: Upstream project
      url: https://github.com/prophetse7en/clonarr
  artifacthub.io/images: |
    - name: clonarr
      image: ghcr.io/prophetse7en/clonarr:latest
