nameOverride: ""
fullnameOverride: ""

# qBittorrent Configuration
qbittorrent:
  image: linuxserver/qbittorrent
  tag: latest
  puid: 1000
  pgid: 1000
  webuiPort: 8080
  torrentingPort: 47872
  
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Gluetun VPN Configuration
gluetun:
  image: qmcgaw/gluetun
  tag: latest
  controlServerPort: 8000
      
  env:
    OPENVPN_USER: ""
    OPENVPN_PASSWORD: ""
    # Specify a supported VPN provider to use
    VPN_SERVICE_PROVIDER: ""
    # Comma separated list of regions
    SERVER_REGIONS: ""
    # Enable custom port forwarding code for supported providers
    VPN_PORT_FORWARDING: off
    # For private internet access, set to true to select servers with port forwarding only
    PORT_FORWARD_ONLY: false
    # Public IP echo service API to use
    PUBLICIP_API: ipinfo
    # Optional API token for the public IP echo service to increase rate limiting
    PUBLICIP_API_TOKEN: ""
  secret:
    # Name of existing secret to use for OpenVPN and IP API credentials.
    existingSecret: ""
    # Names of keys in existing secret to use for credentials
    existingKeys:
      openvpnUser: ""
      openvpnPassword: ""
      publicIpApiToken: ""
  
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Persistence
persistence:
  qbittorrent:
    enabled: true
    # existingClaim: ""
    # storageClass: ""
    label: "qbittorrent" # avoid inverting gluetun and qbittorrent
    size: "1Gi"
    accessMode: "ReadWriteOnce"

    data:
      enabled: true
      # existingClaim: ""
      # storageClass: ""
      size: "500Gi"
      accessMode: "ReadWriteOnce"
      nfs:
        server: "10.0.0.7"
        path: "/torrent"

  gluetun:
    enabled: true
    # existingClaim: ""
    # storageClass: ""
    label: "gluetun" # avoid inverting gluetun and qbittorrent
    size: "1Gi"
    accessMode: "ReadWriteOnce"


# Service Configuration
service:
  type: LoadBalancer
  port: 8080

# Network Policy
networkPolicy:
  enabled: true
