# qBittorrent Configuration
qbittorrent:
  image: linuxserver/qbittorrent
  tag: latest
  puid: 1000
  pgid: 1000
  webuiPort: 8080
  torrentingPort: 47872
  config:
    persistentVolume:
      enabled: true
      # existingClaim: ""
      storageClass: "nfs-client"
      size: "1Gi"
      accessMode: "ReadWriteOnce"
  downloads:
    persistentVolume:
      enabled: true
      # existingClaim: ""
      storageClass: ""
      size: "500Gi"
      accessMode: "ReadWriteOnce"
      nfs:
        server: "10.0.0.7"
        path: "/torrent"

# Gluetun VPN Configuration
gluetun:
  image: qmcgaw/gluetun
  tag: latest
  controlServerPort: 8000
  config:
    persistentVolume:
      enabled: true
      # existingClaim: ""
      storageClass: "nfs-client"
      size: "1Gi"
      accessMode: "ReadWriteOnce"
  env:
    VPN_SERVICE_PROVIDER: "private internet access"
    SERVER_REGIONS: "Switzerland"
    VPN_PORT_FORWARDING: true
  secret:
    name: vpn-credentials

# Service Configuration
service:
  type: LoadBalancer
  port: 8080

# Network Policy
networkPolicy:
  enabled: true
