apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoin-stack.fullname" . }}-config
  labels:
    {{- include "bitcoin-stack.labels" . | nindent 4 }}
data:
  bitcoin.conf: |
    {{- .Values.bitcoind.config | nindent 4 }}
