{{- if and .Values.mempool.enabled .Values.mempool.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bitcoin-stack.fullname" . }}-mempool
  labels:
    {{- include "bitcoin-stack.labels" . | nindent 4 }}
  {{- with .Values.mempool.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.mempool.ingress.className }}
  ingressClassName: {{ .Values.mempool.ingress.className }}
  {{- end }}
  {{- if .Values.mempool.ingress.tls }}
  tls:
    {{- range .Values.mempool.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.mempool.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "bitcoin-stack.fullname" $ }}-mempool-frontend
                port:
                  number: {{ $.Values.mempool.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
