{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-stack.fullname" . }}-metrics
  labels:
    {{- include "bitcoin-stack.labels" . | nindent 4 }}
  {{- with .Values.metrics.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.servicePort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "bitcoin-stack.selectorLabels" . | nindent 4 }}
{{- end }}
