apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitcoind.fullname" . }}-auth
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
type: Opaque
data:
  RPC_USERNAME: {{ .Values.bitcoind.rpc.user | b64enc }}
  RPC_PASSWORD: {{ include "bitcoind.rpcPassword" . | b64enc }}
