apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bitcoin-stack.fullname" . }}
  labels:
    {{- include "bitcoin-stack.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "bitcoin-stack.fullname" . }}
  selector:
    matchLabels:
      {{- include "bitcoin-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bitcoin-stack.selectorLabels" . | nindent 8 }}
    spec:
      # Set termination grace period to 5 minutes to allow graceful shutdown
      terminationGracePeriodSeconds: 300
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitcoin-stack.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}

      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      
      {{- if and .Values.persistence.enabled .Values.volumePermissions.enabled }}
      initContainers:
        - name: volume-permissions
          image: {{ .Values.volumePermissions.image | default "busybox" }}
          imagePullPolicy: {{ .Values.volumePermissions.pullPolicy | default "IfNotPresent" }}
          command: ["sh", "-c", "chmod -R 777 {{ .Values.bitcoind.dataDir }}"]
          volumeMounts:
            - name: data
              mountPath: {{ .Values.bitcoind.dataDir }}
          {{- if .Values.volumePermissions.securityContext.enabled }}
          securityContext:
            {{- toYaml .Values.volumePermissions.securityContext | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{ toYaml .Values.diagnosticMode.command | nindent 12 }}
          args: {{ toYaml .Values.diagnosticMode.args | nindent 12 }}
          {{- else }}
          command:
            - bitcoind
          args:
            - -conf={{ .Values.bitcoind.configFile }}
            - -datadir={{ .Values.bitcoind.dataDir }}
            - -rpccookiefile={{ .Values.bitcoind.cookieFile }}
            - -rpcport={{ .Values.bitcoind.rpc.rpcPort }}
            - -port={{ .Values.bitcoind.rpc.port }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "bitcoin-stack.fullname" . }}-config
          # Add lifecycle hook for graceful shutdown
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "bitcoin-cli -rpccookiefile={{ .Values.bitcoind.cookieFile }} stop && sleep 30"
          ports:
            - name: tcp-p2p
              containerPort: {{ .Values.bitcoind.rpc.port }}
              protocol: TCP
            - name: http-rpc
              containerPort: {{ .Values.bitcoind.rpc.rpcPort }}
              protocol: TCP
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: /v2/info
              port: http-rpc
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /v2/info
              port: http-rpc
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /v2/info
              port: http-rpc
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.bitcoind.dataDir }}
            - name: config
              mountPath: {{ .Values.bitcoind.configFile }}
              subPath: bitcoin.conf
        {{- if .Values.electrs.enabled }}
        - name: electrs
          image: "{{ .Values.electrs.image.repository }}:{{ .Values.electrs.image.tag }}"
          imagePullPolicy: {{ .Values.electrs.image.pullPolicy }}
          command:
            - /scripts/wait-for-bitcoin.sh
          args:
            - /bin/electrs
            - --daemon-rpc-addr=127.0.0.1:{{ .Values.bitcoind.rpc.rpcPort }}
            - --daemon-dir={{ .Values.bitcoind.dataDir }}
            - --db-dir=/electrs
            - --electrum-rpc-addr={{ .Values.electrs.config.electrumRpcAddr }}:{{ .Values.electrs.service.rpcPort }}
            - --http-addr={{ .Values.electrs.config.httpAddr }}:{{ .Values.electrs.service.httpPort }}
            {{- if .Values.electrs.config.jsonrpcEnabled }}
            - --jsonrpc-import
            {{- end }}
            {{- if .Values.electrs.config.corsEnabled }}
            - --cors='*'
            {{- end }}
            {{- if .Values.electrs.config.addressSearch }}
            - --address-search
            {{- end }}
            - --monitoring-addr={{ .Values.electrs.config.monitoringAddr }}:{{ .Values.electrs.service.monitoringPort }}
            {{- if .Values.electrs.config.timestamp }}
            - --timestamp
            {{- end }}
            {{- with .Values.electrs.config.extraArgs }}
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: COOKIE_FILE
              value: "{{ .Values.bitcoind.cookieFile }}"
          ports:
            - name: electrum-rpc
              containerPort: {{ .Values.electrs.service.rpcPort }}
            - name: http
              containerPort: {{ .Values.electrs.service.httpPort }}
            - name: monitoring
              containerPort: {{ .Values.electrs.service.monitoringPort }}
          resources:
            {{- toYaml .Values.electrs.resources | nindent 12 }}
          volumeMounts:
            # Mount the bitcoin data directory to access blockchain data
            - name: data
              mountPath: {{ .Values.bitcoind.dataDir }}
              readOnly: true
            # Mount a separate directory for electrs database
            - name: electrs-db
              mountPath: /electrs
            # Mount scripts
            - name: electrs-scripts
              mountPath: /scripts
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "bitcoin-stack.fullname" . }}-config
        {{- if .Values.electrs.enabled }}
        - name: electrs-scripts
          configMap:
            name: {{ include "bitcoin-stack.fullname" . }}-electrs-scripts
            defaultMode: 0755
        {{- end }}
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- else if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
        {{- if and .Values.electrs.enabled (not .Values.electrs.persistence.enabled) }}
        - name: electrs-db
          emptyDir: {}
        {{- else if and .Values.electrs.enabled .Values.electrs.persistence.enabled .Values.electrs.persistence.existingClaim }}
        - name: electrs-db
          persistentVolumeClaim:
            claimName: {{ .Values.electrs.persistence.existingClaim }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
    - metadata:
        name: data
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        {{- if eq "-" .Values.persistence.storageClass }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
    {{- end }}
    {{- if and .Values.electrs.enabled .Values.electrs.persistence.enabled (not .Values.electrs.persistence.existingClaim) }}
    # Add PVC for electrs database
    - metadata:
        name: electrs-db
      spec:
        accessModes:
        {{- range .Values.electrs.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        {{- if .Values.electrs.persistence.storageClass }}
        {{- if eq "-" .Values.electrs.persistence.storageClass }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.electrs.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.electrs.persistence.size }}
    {{- end }}
