apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoind.fullname" . }}-config
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
data:
  {{- if not .Values.bitcoind.customConfig }}
  BTC_RPCPORT: {{ .Values.bitcoind.rpc.port | quote }}
  BTC_RPCBIND: {{ .Values.bitcoind.rpc.bind | quote }}
  BTC_RPCALLOWIP: {{ .Values.bitcoind.rpc.allowip | quote }}
  BTC_RPCCLIENTTIMEOUT: {{ .Values.bitcoind.rpc.clienttimeout | quote }}
  
  # Network configuration
  BTC_DISABLEWALLET: {{ .Values.bitcoind.disableWallet | int | quote }}
  BTC_TXINDEX: {{ .Values.bitcoind.txIndex | int | quote }}
  
  {{- if .Values.bitcoind.testnet }}
  BTC_TESTNET: "1"
  {{- else if .Values.bitcoind.regtest }}
  BTC_REGTEST: "1"
  {{- end }}
  
  # Advanced indexing
  {{- if .Values.bitcoind.blockfilterIndex }}
  BTC_BLOCKFILTERINDEX: "1"
  {{- end }}
  {{- if .Values.bitcoind.coinstatsIndex }}
  BTC_COINSTATSINDEX: "1"
  {{- end }}
  
  # Cache and performance
  {{- if .Values.bitcoind.dbCache }}
  BTC_DBCACHE: {{ .Values.bitcoind.dbCache | quote }}
  {{- end }}
  
  # Sync options
  {{- with .Values.bitcoind.sync }}
  {{- if .assumevalid }}
  BTC_ASSUMEVALID: {{ .assumevalid | quote }}
  {{- end }}
  BTC_PAR: {{ .parallelblocks | quote }}
  BTC_MAXCONNECTIONS: {{ .maxconnections | quote }}
  BTC_MAXINBOUND: {{ .maxinboundconnections | quote }}
  {{- end }}
  
  # Pruning options
  {{- if .Values.bitcoind.pruning }}
  BTC_PRUNE: {{ .Values.bitcoind.prunesize | quote }}
  {{- end }}
  
  # ZMQ settings
  {{- if .Values.bitcoind.zmq.enabled }}
  BTC_ZMQPUBHASHTX: {{ .Values.bitcoind.zmq.hashTx | quote }}
  BTC_ZMQPUBHASHBLOCK: {{ .Values.bitcoind.zmq.hashBlock | quote }}
  BTC_ZMQPUBRAWTX: {{ .Values.bitcoind.zmq.rawTx | quote }}
  BTC_ZMQPUBRAWBLOCK: {{ .Values.bitcoind.zmq.rawBlock | quote }}
  {{- end }}
  
  # Extra configuration options
  {{- range $key, $value := .Values.bitcoind.extraConfig }}
  BTC_{{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  
  {{- else }}
  bitcoin.conf: |
    {{- .Values.bitcoind.customConfig | nindent 4 }}
  {{- end }}
