apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoind.fullname" . }}-config
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
data:
  bitcoin.conf: |
    {{- .Values.bitcoind.config | nindent 4 }}
