apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoind.fullname" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- if .Values.bitcoind.zmq.enabled }}
    - port: {{ .Values.service.zmqPort }}
      targetPort: zmq
      protocol: TCP
      name: zmq
    {{- end }}
  selector:
    {{- include "bitcoind.selectorLabels" . | nindent 4 }}
