apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bitcoind.fullname" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "bitcoind.fullname" . }}
  selector:
    matchLabels:
      {{- include "bitcoind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bitcoind.selectorLabels" . | nindent 8 }}
    spec:
      # Set termination grace period to 5 minutes to allow graceful shutdown
      terminationGracePeriodSeconds: 300
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitcoind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Add lifecycle hook for graceful shutdown
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "bitcoin-cli -rpcuser=${BTC_RPCUSER} -rpcpassword=${BTC_RPCPASSWORD} stop && sleep 30"
          envFrom:
            - secretRef:
                name: {{ include "bitcoind.fullname" . }}-auth
            - configMapRef:
                name: {{ include "bitcoind.fullname" . }}-config
          {{- if not .Values.bitcoind.customConfig }}
          env:
            - name: BTC_RPCUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "bitcoind.fullname" . }}
                  key: rpcuser
            - name: BTC_RPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bitcoind.fullname" . }}
                  key: rpcpassword
          {{- end }}
          ports:
            - name: tcp-p2p
              containerPort: 8333
              protocol: TCP
            - name: http-rpc
              containerPort: {{ .Values.bitcoind.rpc.port }}
              protocol: TCP
            {{- if .Values.bitcoind.zmq.enabled }}
            - name: zmq
              containerPort: 28333
              protocol: TCP
            {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            {{- if eq .Values.probes.startup.type "httpGet" }}
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http-rpc
            {{- else if eq .Values.probes.startup.type "tcpSocket" }}
            tcpSocket:
              port: http-rpc
            {{- else if eq .Values.probes.startup.type "exec" }}
            exec:
              command: {{ .Values.probes.startup.command }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- if eq .Values.probes.liveness.type "httpGet" }}
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http-rpc
            {{- else if eq .Values.probes.liveness.type "tcpSocket" }}
            tcpSocket:
              port: http-rpc
            {{- else if eq .Values.probes.liveness.type "exec" }}
            exec:
              command: {{ .Values.probes.liveness.command }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            {{- if eq .Values.probes.readiness.type "httpGet" }}
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http-rpc
            {{- else if eq .Values.probes.readiness.type "tcpSocket" }}
            tcpSocket:
              port: http-rpc
            {{- else if eq .Values.probes.readiness.type "exec" }}
            exec:
              command: {{ .Values.probes.readiness.command }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.paths.dataDir }}
            {{- if .Values.bitcoind.customConfig }}
            - name: config
              mountPath: {{ .Values.paths.configFile }}
              subPath: bitcoin.conf
            {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.metrics.image }}"
          imagePullPolicy: {{ .Values.metrics.pullPolicy }}
          args:
            - "--bitcoind.addr=http://localhost:{{ .Values.bitcoind.rpc.port }}"
            - "--bitcoind.user=$(BTC_RPCUSER)"
            - "--bitcoind.pass=$(BTC_RPCPASSWORD)"
            - "--web.listen-address=:{{ .Values.metrics.port }}"
          env:
            - name: BTC_RPCUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "bitcoind.fullname" . }}-auth
                  key: rpcuser
            - name: BTC_RPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bitcoind.fullname" . }}-auth
                  key: rpcpassword
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
        {{- end }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if .Values.bitcoind.customConfig }}
        - name: config
          configMap:
            name: {{ include "bitcoind.fullname" . }}-config
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
