apiVersion: v2
name: palworld-server
description: A Helm chart for Palworld dedicated server
type: application
version: 1.0.2
appVersion: "v1.2.3"
home: https://github.com/thijsvanloef/palworld-server-docker
icon: https://raw.githubusercontent.com/thijsvanloef/palworld-server-docker/main/.github/assets/palworld-docker-logo.png
keywords:
  - palworld
  - game
  - gameserver
  - dedicated server
maintainers:
  - name: kriegalex
    email: kriegalex@gmail.com
sources:
  - https://github.com/thijsvanloef/palworld-server-docker
