apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    app: {{ include "jellyfin.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8096
  selector:
    app: {{ include "jellyfin.name" . }}
