apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enshrouded-server.fullname" . }}
  labels:
    {{- include "enshrouded-server.labels" . | nindent 4 }}
data:
  SERVER_NAME: "{{ .Values.enshrouded.serverName }}"
  SERVER_IP: "{{ .Values.enshrouded.serverIP }}"
  GAME_PORT: "{{ .Values.enshrouded.gamePort }}"
  QUERY_PORT: "{{ .Values.enshrouded.queryPort }}"
  SERVER_SLOTS: "{{ .Values.enshrouded.maxPlayers }}"
  EXTERNAL_CONFIG: "{{ .Values.enshrouded.externalConfig }}"
  {{- if .Values.configMap.enabled }}
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
