{{- if .Values.enshrouded.serverPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enshrouded-server.fullname" . }}
  labels:
    {{- include "enshrouded-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.enshrouded.serverPassword }}
  SERVER_PASSWORD: {{ .Values.enshrouded.serverPassword | b64enc }}
  {{- end }}
{{- end }}
