apiVersion: v1
kind: Service
metadata:
  name: {{ include "enshrouded-server.fullname" . }}
  labels:
    {{- include "enshrouded-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.gamePort.port }}
      targetPort: {{ .Values.service.gamePort.targetPort }}
      protocol: {{ .Values.service.gamePort.protocol }}
      name: game
      {{- if and (eq .Values.service.type "NodePort") .Values.service.gamePort.nodePort }}
      nodePort: {{ .Values.service.gamePort.nodePort }}
      {{- end }}
    - port: {{ .Values.service.queryPort.port }}
      targetPort: {{ .Values.service.queryPort.targetPort }}
      protocol: {{ .Values.service.queryPort.protocol }}
      name: query
      {{- if and (eq .Values.service.type "NodePort") .Values.service.queryPort.nodePort }}
      nodePort: {{ .Values.service.queryPort.nodePort }}
      {{- end }}
  selector:
    {{- include "enshrouded-server.selectorLabels" . | nindent 4 }}
