apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld-server.fullname" . }}
  labels:
    {{- include "palworld-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      name: game
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.server.rconEnabled }}
    - port: {{ .Values.server.rconPort }}
      targetPort: rcon
      protocol: TCP
      name: rcon
    {{- end }}
    {{- if .Values.server.community }}
    - port: 27015
      targetPort: query
      protocol: UDP
      name: query
    {{- end }}
  selector:
    {{- include "palworld-server.selectorLabels" . | nindent 4 }}
