## Name overrides
# -- Override the name of the chart
nameOverride: ""
# -- Override the full name of the chart
fullnameOverride: ""

## Enshrouded Server Configuration
enshrouded:
  # -- Server name displayed in the server browser
  serverName: "My Enshrouded Server"
  # -- Server password (leave blank for no password)
  serverPassword: "changeme"
  # -- Maximum number of players
  maxPlayers: 16
  # -- Game save interval in seconds
  saveInterval: 300
  # -- Server IP address to bind to
  # @default -- 0.0.0.0
  serverIP: "0.0.0.0"
  # -- Game server port (UDP)
  gamePort: 15636
  # -- Query server port (UDP)
  queryPort: 15637
  # -- TZ environment variable for server time zone
  timeZone: "UTC"

## Enshrouded Extra Server Configuration
configMap:
  # -- Enable additional configuration via ConfigMap
  enabled: true
  # -- Additional environment variables
  # @type -- object
  data: {}

## Image configuration
image:
  # -- Repository for the Enshrouded Server image
  repository: sknnr/enshrouded-dedicated-server
  # -- Specify a tag, defaults to Chart.appVersion
  tag: ""
  # -- Image pull policy
  pullPolicy: Always

# -- ImagePullSecrets for private docker registry
imagePullSecrets: []

## ServiceAccount configuration
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations to add to pods
podAnnotations: {}

## Pod security context
podSecurityContext:
  # -- Group ID to run the container
  fsGroup: 10000
  # -- User ID to run the container
  runAsUser: 10000

## Container security context
securityContext:
  # -- Prevent privilege escalation
  allowPrivilegeEscalation: false
  capabilities:
    # -- Linux capabilities to remove
    drop:
      - ALL

## Service configuration
service:
  # -- Service type
  # @valid -- "ClusterIP" "NodePort" "LoadBalancer" "ExternalName"
  type: LoadBalancer
  # -- Annotations for the service
  annotations: {}
  # -- Game port configuration
  gamePort:
    # -- Port exposed by the service
    port: 15636
    # -- Port targetted on the pods
    targetPort: 15636
    # -- Protocol used by the port
    protocol: UDP
  # -- Query port configuration
  queryPort:
    # -- Port exposed by the service
    port: 15637
    # -- Port targetted on the pods
    targetPort: 15637
    # -- Protocol used by the port
    protocol: UDP
  # -- LoadBalancer IP (optional, cloud specific)
  loadBalancerIP: ""
  # -- Specify the allowed IPs for LoadBalancer
  loadBalancerSourceRanges: []
  # -- Use nodePort to expose the service at a static port on each node
  # nodePort: 30000

# -- Resource requests and limits
# @description -- We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube.
resources: {}
  # limits:
  #   memory: 12Gi
  # requests:
  #   cpu: 4000m
  #   memory: 4Gi

## Persistence configuration
persistence:
  # -- Enable persistence using Persistent Volume Claims
  enabled: true
  # -- StorageClass for PVC
  # @description -- If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined or null, no storageClassName spec is set, choosing the default provisioner
  storageClassName: ""
  # -- Access mode for the volume
  accessModes:
    - ReadWriteOnce
  # -- Size of persistent volume claim
  size: 10Gi
  # -- Annotations for PVC
  annotations: {}
  # -- Existing PVC to use (required if persistence.enabled is true)
  existingClaim: ""

# -- Node selector for pod assignment
# @type -- object
nodeSelector: {}

# -- Tolerations for pod assignment
# @type -- array
tolerations: []

# -- Affinity for pod assignment
# @type -- object
affinity: {}

## Update strategy
updateStrategy:
  # -- Update strategy
  # @valid -- "RollingUpdate" "Recreate"
  type: RollingUpdate
  # -- Rolling update configuration parameters
  rollingUpdate:
    # -- Maximum number of pods that can be unavailable during the update
    maxUnavailable: 1
    # -- Maximum number of new pods that can be created during the update
    maxSurge: 0

## Pod Disruption Budget
podDisruptionBudget:
  # -- Enable PodDisruptionBudget
  enabled: false
  # -- Minimum available pods
  minAvailable: 1
  # -- Maximum unavailable pods
  # maxUnavailable: 1

# -- Probe configuration
startupProbe:
  # -- Enable startupProbe
  enabled: true
  # -- Initial delay before probing
  initialDelaySeconds: 30
  # -- Period between probes
  periodSeconds: 10
  # -- Timeout for each probe
  timeoutSeconds: 5
  # -- Number of failures before giving up
  # @description -- Allow up to 5 minutes for initial startup
  failureThreshold: 30

livenessProbe:
  # -- Enable livenessProbe
  enabled: false
  # -- Initial delay before probing
  initialDelaySeconds: 60
  # -- Period between probes
  periodSeconds: 20
  # -- Timeout for each probe
  timeoutSeconds: 5
  # -- Number of failures before giving up
  # @description -- Allow up to 2 minutes for initial startup
  failureThreshold: 6

readinessProbe:
  # -- Enable readinessProbe
  enabled: true
  # -- Initial delay before probing
  initialDelaySeconds: 60
  # -- Period between probes
  periodSeconds: 15
  # -- Timeout for each probe
  timeoutSeconds: 5
  # -- Number of failures before giving up
  # @description -- Allow up to 5 minutes for readiness
  failureThreshold: 20
