apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent-gluetun.fullname" . }}
  labels:
    app: {{ include "qbittorrent-gluetun.name" . }}
    chart: {{ include "qbittorrent-gluetun.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "qbittorrent-gluetun.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "qbittorrent-gluetun.name" . }}
    spec:
      containers:
      - name: gluetun
        image: "{{ .Values.gluetun.image }}:{{ .Values.gluetun.tag }}"
        env:
        - name: VPN_SERVICE_PROVIDER
          value: {{ .Values.gluetun.env.VPN_SERVICE_PROVIDER | quote }}
        - name: SERVER_REGIONS
          value: {{ .Values.gluetun.env.SERVER_REGIONS | quote }}
        - name: VPN_PORT_FORWARDING
          value: {{ .Values.gluetun.env.VPN_PORT_FORWARDING | quote }}
        - name: PORT_FORWARD_ONLY
          value: {{ .Values.gluetun.env.PORT_FORWARD_ONLY | quote }}
        - name: PUBLICIP_API
          value: {{ .Values.gluetun.env.PUBLICIP_API | quote }}
        {{- if .Values.gluetun.env.PUBLICIP_API_TOKEN }}
        - name: PUBLICIP_API_TOKEN
          value: {{ .Values.gluetun.env.PUBLICIP_API_TOKEN | quote }}
        {{- end }}
        {{- if .Values.gluetun.env.OPENVPN_USER }}
        - name: OPENVPN_USER
          value: {{ .Values.gluetun.env.OPENVPN_USER | quote }}
        {{- end }}
        {{- if .Values.gluetun.env.OPENVPN_PASSWORD }}
        - name: OPENVPN_PASSWORD
          value: {{ .Values.gluetun.env.OPENVPN_PASSWORD | quote }}
        {{- end }}
        {{- if .Values.gluetun.secret.existingSecret }}
        {{- if .Values.gluetun.secret.existingKeys.openvpnUser }}
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gluetun.secret.existingSecret }}
              key: {{ .Values.gluetun.secret.existingKeys.openvpnUser }}
        {{- end }}
        {{- if .Values.gluetun.secret.existingKeys.openvpnPassword }}
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gluetun.secret.existingSecret }}
              key: {{ .Values.gluetun.secret.existingKeys.openvpnPassword }}
        {{- end }}
        {{- if .Values.gluetun.secret.existingKeys.publicIpApiToken }}
        - name: PUBLICIP_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gluetun.secret.existingSecret }}
              key: {{ .Values.gluetun.secret.existingKeys.publicIpApiToken }}
        {{- end }}
        {{- end }} # existingSecret
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: gluetun-config
          mountPath: /gluetun

      - name: qbittorrent
        image: "{{ .Values.qbittorrent.image }}:{{ .Values.qbittorrent.tag }}"
        env:
        - name: PUID
          value: {{ .Values.qbittorrent.puid | quote }}
        - name: PGID
          value: {{ .Values.qbittorrent.pgid | quote }}
        - name: WEBUI_PORT
          value: {{ .Values.qbittorrent.webuiPort | quote }}
        - name: TORRENTING_PORT
          value: {{ .Values.qbittorrent.torrentingPort | quote }}
        ports:
        - containerPort: {{ .Values.qbittorrent.webuiPort }}
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads

      volumes:
      - name: gluetun-config
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.gluetun.existingClaim }}{{ .Values.persistence.gluetun.existingClaim }}{{- else }}{{ template "qbittorrent-gluetun.fullname" . }}-gluetun{{- end }}
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.qbittorrent.existingClaim }}{{ .Values.persistence.qbittorrent.existingClaim }}{{- else }}{{ template "qbittorrent-gluetun.fullname" . }}-qbittorrent{{- end }}
      - name: downloads
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.qbittorrent.data.existingClaim }}{{ .Values.persistence.qbittorrent.data.existingClaim }}{{- else }}{{ template "qbittorrent-gluetun.fullname" . }}-data{{- end }}
