{{- if .Values.persistence.qbittorrent.data.nfs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "qbittorrent-gluetun.fullname" . }}-data
  labels:
    app: {{ .Release.Name }}-data
spec:
  capacity:
    storage: {{ .Values.persistence.qbittorrent.data.size }}
  accessModes:
    - {{ .Values.persistence.qbittorrent.data.accessMode }}
  nfs:
    server: {{ .Values.persistence.qbittorrent.data.nfs.server }}
    path: {{ .Values.persistence.qbittorrent.data.nfs.path }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.qbittorrent.data.storageClass }}
{{- end }}