apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent-gluetun.fullname" . }}
  labels:
    app: {{ include "qbittorrent-gluetun.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.qbittorrent.webuiPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ include "qbittorrent-gluetun.name" . }}
