name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: read

jobs:
  changes:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: github.repository == 'kriegalex/k8s-charts'
    outputs:
      charts: ${{ steps.filter.outputs.charts }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Artifact Hub lint
        id: ah-lint
        run: |
          wget https://github.com/artifacthub/hub/releases/download/v1.5.0/ah_1.5.0_linux_amd64.tar.gz
          echo 'ad0e44c6ea058ab6b85dbf582e88bad9fdbc64ded0d1dd4edbac65133e5c87da *ah_1.5.0_linux_amd64.tar.gz' | shasum -c
          tar -xzvf ah_1.5.0_linux_amd64.tar.gz ah
          ./ah lint 2>&1 | tee lint_results.txt
          exit_code=${PIPESTATUS[0]}
          echo "### Artifact Hub Lint Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat lint_results.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          rm -f ./ah ./ah_1.5.0_linux_amd64.tar.gz
          exit $exit_code

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/*/Chart.yaml'
              - 'charts/*/values.yaml'
              - 'charts/*/templates/**'

      - name: Summarize changed files
        run: |
          echo "### Changed Files Detection" >> $GITHUB_STEP_SUMMARY
          echo "Changed charts: ${{ steps.filter.outputs.charts }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.filter.outputs.charts }}" == "true" ]; then
            echo "#### Modified Chart Files:" >> $GITHUB_STEP_SUMMARY
            git diff --name-only HEAD~1 HEAD | grep "charts/" >> $GITHUB_STEP_SUMMARY
          fi

  lint-test:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.charts == 'true' && github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Add dependency repositories
        run: |
          helm repo add plex https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
          helm repo add nextcloud https://nextcloud.github.io/helm/
          helm repo add gitea-charts https://dl.gitea.com/charts/
          helm repo add alekc-charts https://charts.alekc.dev
          helm repo add immich https://immich-app.github.io/immich-charts
          helm repo add gabe565 https://charts.gabe565.com
          helm repo update
          
          echo "### Helm Repository Status" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          helm repo list >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "### Changed Charts" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "$changed" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "### No Charts Changed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct lint --target-branch "$base_branch" 2>&1 | tee lint_output.txt
          echo "### Chart Testing Lint Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat lint_output.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --target-branch "$base_branch" 2>&1 | tee install_output.txt
          echo "### Chart Installation Test Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat install_output.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

  release:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: |
      github.ref == 'refs/heads/main' &&
      github.repository == 'kriegalex/k8s-charts' &&
      needs.changes.outputs.charts == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Add dependency repositories
        run: |
          helm repo add plex https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
          helm repo add nextcloud https://nextcloud.github.io/helm/
          helm repo add gitea-charts https://dl.gitea.com/charts/
          helm repo add alekc-charts https://charts.alekc.dev
          helm repo add immich https://immich-app.github.io/immich-charts
          helm repo add gabe565 https://charts.gabe565.com
          helm repo update

      - name: Update dependencies
        run: |
          echo "### Helm Dependency Updates" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          for chart in charts/*/; do
            if [ -f "${chart}Chart.yaml" ]; then
              echo "Updating dependencies for ${chart}"
              helm dependency update "${chart}" 2>&1 | tee -a dep_update.txt
            fi
          done
          cat dep_update.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Run chart-releaser
        id: releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_SKIP_EXISTING: "true"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true

      - name: Update index.yaml
        run: |
          helm repo index . --url https://kriegalex.github.io/k8s-charts/
          
          echo "### Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Repository URL: https://kriegalex.github.io/k8s-charts/" >> $GITHUB_STEP_SUMMARY
          echo "- Release Status: Success" >> $GITHUB_STEP_SUMMARY
          echo "#### Updated Charts:" >> $GITHUB_STEP_SUMMARY
          yq e '.entries | keys | .[]' index.yaml >> $GITHUB_STEP_SUMMARY

      - name: Final Release Summary
        run: |
          echo "### 🎉 Release Completed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "#### Repository Information" >> $GITHUB_STEP_SUMMARY
          echo "- Charts Repository: https://kriegalex.github.io/k8s-charts/" >> $GITHUB_STEP_SUMMARY
          echo "- Release Date: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "#### Installation Instructions" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "helm repo add k8s-charts https://kriegalex.github.io/k8s-charts/" >> $GITHUB_STEP_SUMMARY
          echo "helm repo update" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
