name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: read

jobs:
  changes:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: github.repository == 'kriegalex/k8s-charts'
    outputs:
      charts: ${{ steps.filter.outputs.charts }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Artifact Hub lint
        id: ah-lint
        run: |
          wget https://github.com/artifacthub/hub/releases/download/v1.20.0/ah_1.20.0_linux_amd64.tar.gz
          echo '9027626f19ff9f3ac668f222917130ac885e289e922e1428bfd2e7f066324e31 *ah_1.20.0_linux_amd64.tar.gz' | shasum -c
          tar -xzvf ah_1.20.0_linux_amd64.tar.gz ah
          ./ah lint || exit 1
          rm -f ./ah ./ah_1.20.0_linux_amd64.tar.gz

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/*/Chart.yaml'
              - 'charts/*/values.yaml'
              - 'charts/*/templates/**'

  lint-test:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.charts == 'true' && github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Add dependency repositories
        run: |
          helm repo add plex https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
          helm repo add nextcloud https://nextcloud.github.io/helm/
          helm repo add gitea-charts https://dl.gitea.com/charts/
          helm repo add alekc-charts https://charts.alekc.dev
          helm repo add immich https://immich-app.github.io/immich-charts
          helm repo add gabe565 https://charts.gabe565.com
          helm repo update
          helm repo list

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: changed=$(ct list-changed --target-branch main)

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch main 2>&1

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch main 2>&1

  release:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: |
      github.ref == 'refs/heads/main' &&
      github.repository == 'kriegalex/k8s-charts' &&
      needs.changes.outputs.charts == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Add dependency repositories
        run: |
          helm repo add plex https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
          helm repo add nextcloud https://nextcloud.github.io/helm/
          helm repo add gitea-charts https://dl.gitea.com/charts/
          helm repo add alekc-charts https://charts.alekc.dev
          helm repo add immich https://immich-app.github.io/immich-charts
          helm repo add gabe565 https://charts.gabe565.com
          helm repo update

      - name: Update dependencies
        run: |
          for chart in charts/*/; do
            if [ -f "${chart}Chart.yaml" ]; then
              echo "Updating dependencies for ${chart}"
              helm dependency update "${chart}" 2>&1
            fi
          done

      - name: Run chart-releaser
        id: releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_SKIP_EXISTING: "true"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
